import type { Metadata } from "next";
import { Raleway, Poppins } from 'next/font/google';
import "./globals.css";


const raleway = Raleway({
  subsets: ['latin'],
  weight: ['200', '400', '500', '700'], // ExtraLight, Regular, Medium, Bold
  variable: '--font-raleway',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'], // Light, Regular, Medium, Bold
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable} ${poppins.variable}`}>
      <body >
        {children}
      </body>
    </html>
  );
}
